server:
  port: 8080
  servlet:
    context-path: /auth


spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    locations: classpath:/db/migration  # Thư mục chứa các script migration
    baseline-on-migrate: true

mybatis:
#  mapper-locations: classpath:/mappers/*.xml (chỉ dùng khi không annotate cho interface)
  configuration:
    map-underscore-to-camel-case: true

#classpath:/com/example/**/mapper/*Mapper.xml